{% set name = "pydantic-core" %}
{% set version = "2.14.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydantic_core-{{ version }}.tar.gz
  sha256: 1fd0c1d395372843fba13a51c28e3bb9d59bd7aebfeb17358ffaaa1e4dbbe948

build:
  script:
    # PyPy has weird sysconfigdata name
    - rm -f $PREFIX/lib/pypy$PY_VER/_sysconfigdata.py  # [build_platform != target_platform and target_platform == "linux-ppc64le"]
    - {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=1,<2                         # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ compiler("rust") }}
  host:
    - pip
    - python
    - maturin >=1,<2
    - typing-extensions >=4.6.0  # [python_impl != "pypy"]
    - typing-extensions >=4.6.0,<4.7.0  # [python_impl == "pypy"]
  run:
    - python
    - typing-extensions >=4.6.0  # [python_impl != "pypy"]
    - typing-extensions >=4.6.0,<4.7.0  # [python_impl == "pypy"]

test:
  imports:
    - pydantic_core
  commands:
    - pip check
    - python -c 'from pydantic_core import PydanticUndefinedType'
  requires:
    - pip

about:
  home: https://github.com/pydantic/pydantic-core
  dev_url: https://github.com/pydantic/pydantic-core
  summary: Core validation logic for pydantic written in rust
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
    - samuelcolvin
    - adriangb
    - dmontagu
    - pavelzw
