{% set version = "2.32.0" %}

package:
  name: pydantic-core
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/07/77/e89851bdfcaf13fb1ec4e433a10712389a92421f1dd06bea3377770c1e30/pydantic_core-{{ version }}.tar.gz
  sha256: db0bbb6014de6fad1283405d3ad2b14a1c3ac850ff493e8292b7705080331316

build:
  script:
    # PyPy has weird sysconfigdata name
    - rm -f $PREFIX/lib/pypy$PY_VER/_sysconfigdata.py  # [build_platform != target_platform and target_platform == "linux-ppc64le"]
    - export CARGO_PROFILE_RELEASE_STRIP=symbols  # [unix]
    - export RUSTFLAGS="$CARGO_BUILD_RUSTFLAGS"   # [unix]
    - set CARGO_PROFILE_RELEASE_STRIP=symbols  # [win]
    - {{ PYTHON }} -m pip install . -vv
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=1,<2                         # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler("rust") }}
    - cargo-bundle-licenses
  host:
    - pip
    - python
    - maturin >=1,<2
    - typing-extensions  >=4.6.0,!=4.7.0
  run:
    - python
    - typing-extensions >=4.6.0,!=4.7.0

test:
  imports:
    - pydantic_core
  commands:
    - pip check
    - python -c "from pydantic_core import PydanticUndefinedType"
  requires:
    - pip

about:
  home: https://github.com/pydantic/pydantic-core
  dev_url: https://github.com/pydantic/pydantic-core
  summary: Core validation logic for pydantic written in rust
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
    - samuelcolvin
    - adriangb
    - dmontagu
    - pavelzw
