{% set name = "pydantic-core" %}
{% set version = "0.17.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydantic_core-{{ version }}.tar.gz
  sha256: d7f4289d0a514b42e364c5ceaab7d16d08d78128a8b7372486931275512deeef
  patches:
    # https://github.com/pydantic/pydantic-core/pull/469
    - 0001-build-Use-PYTHON-to-determine-the-correct-python-exe.patch

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=0.14,<0.15                   # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ compiler("rust") }}
  host:
    - pip
    - python
    - maturin >=0.14,<0.15
    - typing_extensions
  run:
    - python
    - typing_extensions  # [py<311]

test:
  imports:
    - pydantic_core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pydantic/pydantic-core
  dev_url: https://github.com/pydantic/pydantic-core
  summary: Core validation logic for pydantic written in rust
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
    - samuelcolvin
    - adriangb
    - dmontagu
