schema_version: 1

context:
  name: pydantic-core
  version: "2.34.0"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace("-", "_") }}-${{ version }}.tar.gz
  sha256: f5c797f6e083e1abb9b6c30533477e85c951b4169dc68c99cb8ebd8d16d8f3ca

build:
  number: 0
  script:
    - if: unix
      then:
        - export CARGO_PROFILE_RELEASE_STRIP=symbols
        - export CARGO_PROFILE_RELEASE_LTO=fat
    - if: win
      then:
        - set CARGO_PROFILE_RELEASE_STRIP=symbols
        - set CARGO_PROFILE_RELEASE_LTO=fat
    - python -m pip install . -vv
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - maturin >=1,<2
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - ${{ compiler("rust") }}
    - cargo-bundle-licenses
  host:
    - pip
    - python
    - maturin >=1,<2
    - typing-extensions >=4.6.0,!=4.7.0
  run:
    - python
    - typing-extensions >=4.6.0,!=4.7.0

tests:
  - python:
      imports:
        - pydantic_core
  - requirements:
      run:
        - pip
    script:
      - pip check
      - python -c "from pydantic_core import PydanticUndefinedType"

about:
  summary: Core validation logic for pydantic written in rust
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  homepage: https://github.com/pydantic/pydantic-core
  repository: https://github.com/pydantic/pydantic-core

extra:
  recipe-maintainers:
    - xhochy
    - samuelcolvin
    - adriangb
    - dmontagu
    - pavelzw
