schema_version: 1

context:
  name: pydantic-core
  version: "2.43.0"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/c3/cb/1b14f08cf19b763af46d3e0050af1d6c456936a56af33df3c2a384e427b3/pydantic_core-${{ version }}.tar.gz
  sha256: 3cb711c1b92c98da3ea8e783410cc34a17e7d6aaf4f695544e82b7af3ef41f50

build:
  skip: python == "3.14.* *_cp314t" and (target_platform == "linux-aarch64" or target_platform == "linux-ppc64le")
  number: 0
  script:
    - if: unix
      then:
        - export CARGO_PROFILE_RELEASE_STRIP=symbols
        - export CARGO_PROFILE_RELEASE_LTO=fat
    - if: win
      then:
        - set CARGO_PROFILE_RELEASE_STRIP=symbols
        - set CARGO_PROFILE_RELEASE_LTO=fat
    - if: build_platform != target_platform and unix and python is startingwith('3.14')
      then:
        - rm -f $PREFIX/lib/python3.14/build-details.json
    - python -m pip install . -vv
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - maturin >=1,<2
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - ${{ compiler("rust") }}
    - cargo-bundle-licenses
  host:
    - pip
    - python
    - maturin >=1,<2
    - typing-extensions >=4.6.0,!=4.7.0
  run:
    - python
    - typing-extensions >=4.6.0,!=4.7.0

tests:
  - python:
      imports:
        - pydantic_core
  - requirements:
      run:
        - pip
    script:
      - pip check
      - python -c "from pydantic_core import PydanticUndefinedType"

about:
  summary: Core validation logic for pydantic written in rust
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  homepage: https://github.com/pydantic/pydantic/tree/main/pydantic-core
  repository: https://github.com/pydantic/pydantic/tree/main/pydantic-core

extra:
  recipe-maintainers:
    - xhochy
    - samuelcolvin
    - adriangb
    - dmontagu
    - pavelzw
