schema_version: 1

context:
  name: pydantic-core
  version: 2.32.0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace("-", "_") }}-${{ version }}.tar.gz
  sha256: db0bbb6014de6fad1283405d3ad2b14a1c3ac850ff493e8292b7705080331316

build:
  number: 1
  script:
    - if: unix
      then:
        - export CARGO_PROFILE_RELEASE_STRIP=symbols
        - export CARGO_PROFILE_RELEASE_LTO=fat
        - export RUSTFLAGS=\"$CARGO_BUILD_RUSTFLAGS\"
    - if: win
      then:
        - set CARGO_PROFILE_RELEASE_STRIP=symbols
        - set CARGO_PROFILE_RELEASE_LTO=fat
    - ${{ PYTHON }} -m pip install . -vv
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - maturin >=1,<2
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - ${{ compiler("rust") }}
    - cargo-bundle-licenses
  host:
    - pip
    - python
    - maturin >=1,<2
    - typing-extensions  >=4.6.0,!=4.7.0
  run:
    - python
    - typing-extensions >=4.6.0,!=4.7.0

tests:
  - python:
      imports:
        - pydantic_core
  - requirements:
      run:
        - pip
    script:
      - pip check
      - "python -c \"from pydantic_core import PydanticUndefinedType\""

about:
  summary: Core validation logic for pydantic written in rust
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  homepage: https://github.com/pydantic/pydantic-core
  repository: https://github.com/pydantic/pydantic-core

extra:
  recipe-maintainers:
    - xhochy
    - samuelcolvin
    - adriangb
    - dmontagu
    - pavelzw
